name: Service Promotion
run-name: Promoting Spark services from lower to higher environments

on:
  workflow_dispatch:

jobs:
  impex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry and dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run ImpEx API script
        env:
          FROM_SETTINGS: ${{ vars.FROM_SPARK_SETTINGS }}
          BEARER_TOKEN: ${{ secrets.FROM_BEARER_TOKEN }}
          TO_SETTINGS: ${{ vars.TO_SPARK_SETTINGS }}
          TO_OAUTH: ${{ secrets.TO_OAUTH_CREDS }}
        run: poetry run python impex.py "$FROM_SETTINGS" "$BEARER_TOKEN" "$TO_SETTINGS" "$TO_OAUTH"
