name: CI

on:
  push:
    branches: [dev]

jobs:
  test:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye-up.com/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
        env:
          RYE_VERSION: 0.33.0
          RYE_INSTALL_OPTION: '--yes'

      - name: Install dependencies
        run: rye sync --all-features

      - name: Run linters
        run: rye run lint

      - name: Ensure importability
        run: |
          rye run python -c 'import cspark'
          rye run demo

      - name: Run tests
        run: rye test
